name: apps
services:
  ### DJANGO APPS ###
  webapp:
    build: ./webapp
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - TRACING_HOST=jaeger
      - TRACING_PORT=14268
    volumes:
      - ./webapp:/webapp
    ports:
      - 8000:8000
    depends_on:
      - webapi
    networks:
      - apps
      - observability
    labels:
      - monitor_enable=true
      - monitor_project=mlt_django
      - monitor_env=development
      - monitor_app=webapp
      - prometheus___metrics_path__=/metrics

  webapi:
    build: ./webapi
    command: python manage.py runserver 0.0.0.0:8001
    environment:
      - TRACING_HOST=jaeger
      - TRACING_PORT=14268
    volumes:
      - ./webapi:/webapi
    ports:
      - 8001:8001
    networks:
      - apps
      - observability
    labels:
      - monitor_enable=true
      - monitor_project=mlt_django
      - monitor_env=development
      - monitor_app=webapi
      - prometheus___metrics_path__=/metrics

networks:
  apps:
    name: django_apps
  observability:
    name: observability
    external: true
