name: apps
services:
  ### DJANGO APPS ###
  webapp:
    build: ./webapp
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - TRACING_HOST=jaeger-agent
      - TRACING_PORT=6831
    volumes:
      - ./webapp:/webapp
    ports:
      - 8000:8000
      - 8080:8080
    depends_on:
      - webapi
    networks:
      - apps
      - observability
    labels:
      - prometheus_job=apps_webapp
      - prometheus_project=mlt_test
      - prometheus_env=development
      - prometheus___metrics_path__=/metrics
      - promtail_enable=true
      - promtail_job=apps_webapp
      - promtail_project=mlt_test
      - promtail_env=development

  webapi:
    build: ./webapi
    command: python manage.py runserver 0.0.0.0:8001
    environment:
      - TRACING_HOST=jaeger-agent
      - TRACING_PORT=6831
    volumes:
      - ./webapi:/webapi
    ports:
      - 8001:8001
    networks:
      - apps
      - observability
    labels:
      - prometheus_job=apps_webapi
      - prometheus_project=mlt_test
      - prometheus_env=development
      - prometheus___metrics_path__=/metrics
      - promtail_enable=true
      - promtail_job=apps_webapi
      - promtail_project=mlt_test
      - promtail_env=development

networks:
  apps:
    name: django_apps
  observability:
    name: observability
    external: true
