name: observability
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/datasources/dashboard.yaml
    depends_on:
      # - tempo
      - loki
      - prometheus
      - jaeger
    networks:
      - observability

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16686:16686
      - 6831:6831
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:0444
    command: --config.file=/etc/prometheus/prometheus.yaml
    user: root
    networks:
      - observability

  # tempo:
  #   image: grafana/tempo:latest
  #   ports:
  #     - "14268:14268"
  #   command:
  #     - -config.file=/etc/tempo/tempo.yaml
  #   volumes:
  #     - ./tempo/tempo.yaml:/etc/tempo/tempo.yaml

networks:
  observability:
    name: observability
