# https://prometheus.io/docs/prometheus/latest/configuration/configuration/

global:
  scrape_interval: 10s
  scrape_timeout: 5s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: docker_host
    # https://docs.docker.com/config/daemon/prometheus/
    static_configs:
      - targets:
        - host.docker.internal:9323
  - job_name: docker_containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_monitor_enable]
        regex: .+
        action: keep
      - regex: __meta_docker_container_label_monitor_enable
        action: labeldrop
      - regex: __meta_docker_container_label_monitor_(.+)
        action: labelmap
        replacement: $1
      - regex: __meta_docker_container_label_prometheus_(.+)
        action: labelmap
        replacement: $1
  # - job_name: docker_dns
  #   dns_sd_configs:
  #     - names:
  #         - webapp
  #       type: A
  #       port: 8000
  #     - names:
  #         - webapi
  #       type: A
  #       port: 8001
