{
 "title": "Django Simple",
 "tags": [
  "Django",
  "Web"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Project", "query": { "query": "label_values(project)" } },
   {
    "name": "Environment",
    "query": {
     "query": "label_values({project=\"$Project\"},env)"
    }
   },
   {
    "name": "App",
    "query": {
     "query": "label_values({project=\"$Project\"},app)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_transport_total{project=~\"$Project\",env=~\"$Environment\",app=~\"$App\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(django_http_responses_total_by_status_total{project=~\"$Project\",env=~\"$Environment\",app=~\"$App\"}[$__rate_interval])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request by method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum by (method)(irate(django_http_requests_total_by_method_total{project=~\"$Project\",env=~\"$Environment\",app=~\"$App\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Latency distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{project=~\"$Project\",env=~\"$Environment\",app=~\"$App\"}[$__rate_interval])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.70, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{project=~\"$Project\",env=~\"$Environment\",app=~\"$App\"}[$__rate_interval])) by (le))",
     "legendFormat": "70"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(django_http_requests_latency_seconds_by_view_method_bucket{project=~\"$Project\",env=~\"$Environment\",app=~\"$App\"}[$__rate_interval])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Requests by view",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(django_http_requests_total_by_view_transport_method_total{project=~\"$Project\",env=~\"$Environment\",app=~\"$App\"}[$__rate_interval])",
     "legendFormat": "{{view}}"
    }
   ]
  }
 ]
}